spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dbAPI
    username: postgres
    password: 704980
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: false
#springdoc:
#  pathsToMatch: api/**/**
#  swagger-ui:
#    use-root-path: true